### PR TITLE
add keyboard shortcut and lower delay for automatic update

### PR DESCRIPTION
**Pull request by mhelleboid**
I find this plugin useful!

And I sometimes change the expression in the title and wanted to more easily update the due date by using the keyboard.

Also The 5sec delay seems too high for me, so I'm using a 1sec delay, maybe this could be improved by proposing a settings for this.

### CODE REVIEW

**Review by zph — APPROVED** [review]
LGTM, thanks for the contribution! I'll reformat it to replace tabs w/ spaces for consistency after merging.

I'll add you as a contributor on project with commit bit. Please push changes as PRs for review as you make improvements.

**Comment by zph** [comment]
Version 1.0.8 is pushed w/ these changes 🐎 

https://www.npmjs.com/package/joplin-plugin-auto-alarm

**Comment by zph** [comment]
@mhelleboid Invite sent with invitation as project collaborator.

**Comment by mhelleboid** [comment]
@zph, Thanks for the quick reply and the invite

**Pull request merged**
